export const perfectScorePhrases = [
    "Perfection!",
    "A GeoGenius!",
    "Nailed it!",
    "Top of the world!",
    "Flawless victory!",
    "Guessing Guru!",
    "Master Mapper!",
    "Unstoppable Geographer!",
    "Global Grandmaster!",
    "Guesswork God!",
    "Absolute Ace!",
    "Pinpoint Perfectionist!",
    "Spectacular Score!",
    "Mapping Maestro!",
    "Geography Genius!",
    "Location Luminary!",
    "Sensational Success!",
    "Legendary Locator!",
    "Magnificent Mastery!",
    "Incredible Intuition!",
    "Stellar Spotter!",
    "World Wizard!",
    "Unrivaled Understanding!",
    "Phenomenal Performance!",
    "Perfect Player!",
    "Geography Grandmaster!",
    "Supreme Spotter!",
    "Geo Wizard!",
];

export const highScorePhrases = [
    "Great job!",
    "Impressive!",
    "You've got this!",
    "Almost perfect!",
    "On a roll!",
    "World-class guesser!",
    "So close to perfection!",
    "Rocking the globe!",
    "Exquisite execution!",
    "Nearly there!",
    "Geography superstar!",
    "Worldly wise!",
    "Terrific tally!",
    "Superb spotting!",
    "Sharp as a tack!",
    "Guessing giant!",
    "Close to the crown!",
    "Terrific traveller!",
    "Mapping magician!",
    "Location legend!",
    "Savvy score!",
    "Outstanding observer!",
    "Fantastic feat!",
    "Just a step away!",
    "Unveiling virtuoso!",
    "Remarkable results!",
    "Global guru!",
];

export const midScorePhrases = [
    "Not bad!",
    "Keep going!",
    "On the right path!",
    "Getting there!",
    "Nice effort!",
    "Halfway around the world!",
    "Good hustle!",
    "Solid start!",
    "Decent job!",
    "Good groundwork!",
    "Keep exploring!",
    "Promising player!",
    "Steady strides!",
    "Stay on course!",
    "Respectable run!",
    "Keep the momentum!",
    "Globetrotting goodness!",
    "Heading in the right direction!",
    "You're getting warmer!",
    "Hang in there!",
    "Better and better!",
    "Keep spinning that globe!",
    "Journey on!",
    "The world's your oyster!",
    "Not too shabby!",
    "Gaining ground!",
    "Inching towards glory!",
];

export const lowScorePhrases = [
    "Room to improve!",
    "More globe-trotting!",
    "Practice makes perfect!",
    "Next time, you'll nail it!",
    "Keep spinning that globe!",
    "Almost had it!",
    "A valiant attempt!",
    "Better luck next round!",
    "Keep practicing!",
    "Don't stop exploring!",
    "Don't lose heart!",
    "The world is still yours to conquer!",
    "Guess, learn, repeat!",
    "Every guess is a step forward!",
    "Your journey has just begun!",
    "Mistakes are proof that you're trying!",
    "You've got potential!",
    "Persistence is key!",
    "Failure is the first step towards success!",
    "Every cloud has a silver lining!",
    "Keep discovering!",
    "Your luck will turn!",
    "Chin up, champ!",
    "Experience is the best teacher!",
    "Never stop believing!",
    "Tomorrow is another day!",
    "Upwards and onwards!",
];

export const minScorePhrases = [
    "Oops!",
    "Globe-trotting in the dark!",
    "Better luck next time!",
    "Keep trying!",
    "Don't give up!",
    "Next stop, Geography 101!",
    "We all start somewhere!",
    "The world is still big, keep learning!",
    "The sun will rise and we will try again!",
    "Never stop exploring!",
    "You'll hit the mark next time!",
    "Rough start, but don't lose heart!",
    "You learn more from failure than from success!",
    "Mistakes are stepping stones to improvement!",
    "You're only getting started!",
    "Every guess is progress!",
    "Brace up and try again!",
    "Remember, Rome wasn't built in a day!",
    "A stumble may prevent a fall!",
    "The expert in anything was once a beginner!",
    "The road to success is always under construction!",
    "Turn the page and start a new chapter!",
    "You only fail when you stop trying!",
    "Dust yourself off and try again!",
    "Don't be discouraged, you're learning!",
];
